// Mock data for spaces - used when database is not available
// This allows the site to work without environment variables for preview/feedback

export const MOCK_SPACES = [
  {
    id: 'mock-1',
    name: 'Meeting Room S',
    nameEn: 'Meeting Room S (1-10 people)',
    nameFr: 'Salle de Réunion S (1-10 personnes)',
    description: 'Small meeting room for up to 10 people',
    descriptionEn: 'Small meeting room for up to 10 people',
    descriptionFr: 'Petite salle de réunion jusqu\'à 10 personnes',
    capacity: 10,
    pricePerHour: 10,
    pricePerDay: 60,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-2',
    name: 'Meeting Room M',
    nameEn: 'Meeting Room M (11-25 people)',
    nameFr: 'Salle de Réunion M (11-25 personnes)',
    description: 'Medium meeting room for 11-25 people',
    descriptionEn: 'Medium meeting room for 11-25 people',
    descriptionFr: 'Salle de réunion moyenne pour 11-25 personnes',
    capacity: 25,
    pricePerHour: 15,
    pricePerDay: 90,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-3',
    name: 'Meeting Room L',
    nameEn: 'Meeting Room L (26-40 people)',
    nameFr: 'Salle de Réunion L (26-40 personnes)',
    description: 'Large meeting room for 26-40 people',
    descriptionEn: 'Large meeting room for 26-40 people',
    descriptionFr: 'Grande salle de réunion pour 26-40 personnes',
    capacity: 40,
    pricePerHour: 20,
    pricePerDay: 120,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café", "Sonorisation"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-4',
    name: 'Meeting Room XL',
    nameEn: 'Meeting Room XL (41-60 people)',
    nameFr: 'Salle de Réunion XL (41-60 personnes)',
    description: 'Extra large meeting room for 41-60 people',
    descriptionEn: 'Extra large meeting room for 41-60 people',
    descriptionFr: 'Très grande salle de réunion pour 41-60 personnes',
    capacity: 60,
    pricePerHour: 25,
    pricePerDay: 160,
    amenities: '["Wi-Fi Premium", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café", "Sonorisation", "Assistance Technique"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-5',
    name: 'Co-working Space',
    nameEn: 'Co-working Space',
    nameFr: 'Espace de Coworking',
    description: 'Shared co-working space with daily access',
    descriptionEn: 'Shared co-working space with daily access',
    descriptionFr: 'Espace de coworking partagé avec accès journalier',
    capacity: 1,
    pricePerHour: 0.5,
    pricePerDay: 3,
    amenities: '["Wi-Fi", "Mobilier & espaces communs", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export type MockSpace = typeof MOCK_SPACES[0];
