// Mock data for space setups - used when database is not available
// This allows the site to work without environment variables for preview/feedback
// Note: These represent different configurations of the same physical room

export const MOCK_SPACES = [
  {
    id: 'mock-1',
    name: 'Setup S',
    nameEn: 'Setup S (1-10 people)',
    nameFr: 'Configuration S (1-10 personnes)',
    description: 'Room configured for up to 10 people',
    descriptionEn: 'Room configured for up to 10 people',
    descriptionFr: 'Salle configurée pour jusqu\'à 10 personnes',
    capacity: 10,
    pricePerHour: 10,
    pricePerDay: 60,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-2',
    name: 'Setup M',
    nameEn: 'Setup M (11-25 people)',
    nameFr: 'Configuration M (11-25 personnes)',
    description: 'Room configured for 11-25 people',
    descriptionEn: 'Room configured for 11-25 people',
    descriptionFr: 'Salle configurée pour 11-25 personnes',
    capacity: 25,
    pricePerHour: 15,
    pricePerDay: 90,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-3',
    name: 'Setup L',
    nameEn: 'Setup L (26-40 people)',
    nameFr: 'Configuration L (26-40 personnes)',
    description: 'Room configured for 26-40 people',
    descriptionEn: 'Room configured for 26-40 people',
    descriptionFr: 'Salle configurée pour 26-40 personnes',
    capacity: 40,
    pricePerHour: 20,
    pricePerDay: 120,
    amenities: '["Wi-Fi", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café", "Sonorisation"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-4',
    name: 'Setup XL',
    nameEn: 'Setup XL (41-60 people)',
    nameFr: 'Configuration XL (41-60 personnes)',
    description: 'Room configured for 41-60 people',
    descriptionEn: 'Room configured for 41-60 people',
    descriptionFr: 'Salle configurée pour 41-60 personnes',
    capacity: 60,
    pricePerHour: 25,
    pricePerDay: 160,
    amenities: '["Wi-Fi Premium", "Projecteur/Écran", "Whiteboard", "Video Conferencing", "Café", "Sonorisation", "Assistance Technique"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-5',
    name: 'Co-working Space',
    nameEn: 'Co-working Space',
    nameFr: 'Espace de Coworking',
    description: 'Shared co-working space with daily access',
    descriptionEn: 'Shared co-working space with daily access',
    descriptionFr: 'Espace de coworking partagé avec accès journalier',
    capacity: 1,
    pricePerHour: 0.5,
    pricePerDay: 3,
    amenities: '["Wi-Fi", "Mobilier & espaces communs", "Café"]',
    imageUrl: null,
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export type MockSpace = typeof MOCK_SPACES[0];
